### ISSUE TITLE
TODO : 記事に必要な一覧

### ISSUE THREAD

**Issue by koinunopochi** [koinunopochi/DevDiaryBlog#316]
- [ ] エンティティの実装
  - [ ] Article エンティティの実装
  - [ ] Category エンティティの実装
  - [ ] Tag エンティティの実装
  - [ ] Author エンティティの実装
  - [ ] Comment エンティティの実装
  - [ ] Series エンティティの実装
  - [ ] SeriesArticle エンティティの実装

- [ ] 値オブジェクトの実装
  - [ ] ArticleId の実装
  - [ ] ArticleTitle の実装
  - [ ] ArticleContent の実装
  - [ ] ArticleStatus の実装
  - [ ] ArticleTagList の実装
  - [ ] CategoryId の実装
  - [ ] CategoryName の実装
  - [ ] CategoryDescription の実装
  - [ ] CategoryTagList の実装
  - [ ] TagId の実装
  - [ ] TagName の実装
  - [ ] AuthorId の実装
  - [ ] AuthorName の実装
  - [ ] EmailAddress の実装
  - [ ] AuthorBio の実装
  - [ ] CommentId の実装
  - [ ] CommentContent の実装
  - [ ] DateTime の実装
  - [ ] SeriesId の実装
  - [ ] SeriesTitle の実装
  - [ ] SeriesDescription の実装
  - [ ] SeriesStatus の実装
  - [ ] SeriesArticleId の実装
  - [ ] SeriesOrder の実装

- [ ] 集約の実装
  - [ ] Article 集約の実装
  - [ ] Category 集約の実装
  - [ ] Tag 集約の実装
  - [ ] Author 集約の実装
  - [ ] Series 集約の実装

- [ ] リレーションシップの実装
  - [ ] Article - Category リレーションシップの実装
  - [ ] Article - Tag リレーションシップの実装
  - [ ] Article - Author リレーションシップの実装
  - [ ] Category - Tag リレーションシップの実装
  - [ ] Article - Comment リレーションシップの実装
  - [ ] Comment - Author リレーションシップの実装
  - [ ] Series - Author リレーションシップの実装
  - [ ] Series - SeriesArticle リレーションシップの実装
  - [ ] SeriesArticle - Article リレーションシップの実装

- [ ] データベースマイグレーションの作成
  - [ ] Articles テーブルのマイグレーション
  - [ ] Categories テーブルのマイグレーション
  - [ ] Tags テーブルのマイグレーション
  - [ ] Authors テーブルのマイグレーション
  - [ ] Comments テーブルのマイグレーション
  - [ ] Series テーブルのマイグレーション
  - [ ] SeriesArticles テーブルのマイグレーション
  - [ ] 中間テーブル（article_tag, category_tag）のマイグレーション

- [ ] リポジトリの実装
  - [ ] ArticleRepository の実装
  - [ ] CategoryRepository の実装
  - [ ] TagRepository の実装
  - [ ] AuthorRepository の実装
  - [ ] CommentRepository の実装
  - [ ] SeriesRepository の実装
  - [ ] SeriesArticleRepository の実装

- [ ] ユースケースの実装
  - [ ] 記事の作成、編集、削除、公開、アーカイブ
  - [ ] カテゴリの作成、編集、削除
  - [ ] タグの作成、編集、削除
  - [ ] 著者の登録、編集、削除
  - [ ] コメントの投稿、編集、削除
  - [ ] シリーズの作成、編集、削除
  - [ ] シリーズへの記事の追加、削除、順序変更

- [ ] API エンドポイントの実装
  - [ ] 記事関連のエンドポイント
  - [ ] カテゴリ関連のエンドポイント
  - [ ] タグ関連のエンドポイント
  - [ ] 著者関連のエンドポイント
  - [ ] コメント関連のエンドポイント
  - [ ] シリーズ関連のエンドポイント

- [ ] フロントエンド（React）の実装
  - [ ] 記事一覧ページの作成
  - [ ] 記事詳細ページの作成
  - [ ] 記事作成/編集フォームの作成
  - [ ] カテゴリ管理ページの作成
  - [ ] タグ管理ページの作成
  - [ ] 著者管理ページの作成
  - [ ] コメント機能の実装
  - [ ] シリーズ管理ページの作成

- [ ] テストの実装
  - [ ] ユニットテストの作成
  - [ ] 統合テストの作成
  - [ ] E2E テストの作成

**Comment by koinunopochi** [comment]
Authorを既存のUserを利用するように定義しなおしたため、厳密には作成していないが、済みとする
